package mazerunner;


import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

public class Fenster extends javax.swing.JFrame {

     /** Creates new form Fenster*/
     
    private Mazerunner runner;
    private JPanel drawingPanel;
    private BorderLayout layout;
    private JButton jbSolve;
    private Solver Solv;
    
    public Fenster() 
    {
        Container pane = getContentPane();
        Solv = new Solver();
        layout = new BorderLayout();
        runner = new Mazerunner();
      
        
        pane.setLayout(layout);
        
        jbSolve = new JButton("Solve");
        jbSolve.addActionListener((ActionEvent e) -> {
            Solv.randomSolver(runner.labyrinthfeld);
        });
        drawingPanel = new Mazerunner();
        
        pane.add(jbSolve, BorderLayout.SOUTH);
        pane.add(drawingPanel, BorderLayout.CENTER);
        
        setSize(800,640);
       // add(drawingPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
